/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lista5.view;

import javax.swing.JOptionPane;
import lista5.model.Ponto;
import lista5.model.Quadrante;

/**
 *
 * @author gabri
 */
public class Tela extends javax.swing.JFrame {

    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTfEixoX = new javax.swing.JTextField();
        jTfEixoY = new javax.swing.JTextField();
        jBtnAvaliar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jCbSobreX = new javax.swing.JCheckBox();
        jCbSobreY = new javax.swing.JCheckBox();
        jCbQuadrante1 = new javax.swing.JCheckBox();
        jCbQuadrante2 = new javax.swing.JCheckBox();
        jCbQuadrante3 = new javax.swing.JCheckBox();
        jCbQuadrante4 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Eixo X:");

        jLabel2.setText("Eixo Y:");

        jTfEixoX.setMinimumSize(new java.awt.Dimension(80, 22));
        jTfEixoX.setPreferredSize(new java.awt.Dimension(80, 22));
        jTfEixoX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTfEixoXActionPerformed(evt);
            }
        });

        jTfEixoY.setMinimumSize(new java.awt.Dimension(80, 22));
        jTfEixoY.setPreferredSize(new java.awt.Dimension(80, 22));
        jTfEixoY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTfEixoYActionPerformed(evt);
            }
        });

        jBtnAvaliar.setText("Avaliar");
        jBtnAvaliar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAvaliarActionPerformed(evt);
            }
        });

        jLabel3.setText("Posição:");

        jCbSobreX.setText("Incide Sobre o Eixo X");
        jCbSobreX.setEnabled(false);

        jCbSobreY.setText("Incide Sobre o Eixo Y");
        jCbSobreY.setEnabled(false);

        jCbQuadrante1.setText("No 1° Quadrante");
        jCbQuadrante1.setEnabled(false);

        jCbQuadrante2.setText("No 2° Quadrante");
        jCbQuadrante2.setEnabled(false);

        jCbQuadrante3.setText("No 3° Quadrante");
        jCbQuadrante3.setEnabled(false);

        jCbQuadrante4.setText("No 4° Quadrante");
        jCbQuadrante4.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTfEixoX, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTfEixoY, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jBtnAvaliar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jCbSobreX)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jCbQuadrante1)
                                .addComponent(jCbSobreY)
                                .addComponent(jCbQuadrante2)
                                .addComponent(jCbQuadrante3)
                                .addComponent(jCbQuadrante4)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTfEixoX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTfEixoY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jBtnAvaliar)))
                .addGap(26, 26, 26)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCbSobreX)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jCbSobreY)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCbQuadrante1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCbQuadrante2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCbQuadrante3)
                .addGap(7, 7, 7)
                .addComponent(jCbQuadrante4)
                .addGap(36, 36, 36))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTfEixoXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTfEixoXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTfEixoXActionPerformed

    private void jTfEixoYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTfEixoYActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTfEixoYActionPerformed

    private void jBtnAvaliarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAvaliarActionPerformed
        try {
            limpar();
            
            int eixoX = Integer.parseInt(jTfEixoX.getText());
            int eixoY = Integer.parseInt(jTfEixoY.getText());
            
            Ponto ponto = new Ponto(eixoX, eixoY);
            
            Quadrante quadrante = ponto.identificarQuadrante();
            
            switch (quadrante) {
                case PRIMEIRO:
                    jCbQuadrante1.setSelected(true);
                    break;
                
                case SEGUNDO:
                    jCbQuadrante2.setSelected(true);
                    break;
                
                case TERCEIRO:
                    jCbQuadrante3.setSelected(true);
                    break;
                    
                case QUARTO:
                    jCbQuadrante4.setSelected(true);
                    break;
                    
                default:
                    jCbSobreX.setSelected(ponto.estaIncidindoSobreX());
                    jCbSobreY.setSelected(ponto.estaIncidindoSobreY());
                    break;
            }
        } catch (IllegalArgumentException error) {
            JOptionPane.showMessageDialog(null, error.getMessage());
        }
    }//GEN-LAST:event_jBtnAvaliarActionPerformed
    
    public void limpar() {
        jCbSobreX.setSelected(false);
        jCbSobreY.setSelected(false);
        jCbQuadrante1.setSelected(false);
        jCbQuadrante2.setSelected(false);
        jCbQuadrante3.setSelected(false);
        jCbQuadrante4.setSelected(false);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAvaliar;
    private javax.swing.JCheckBox jCbQuadrante1;
    private javax.swing.JCheckBox jCbQuadrante2;
    private javax.swing.JCheckBox jCbQuadrante3;
    private javax.swing.JCheckBox jCbQuadrante4;
    private javax.swing.JCheckBox jCbSobreX;
    private javax.swing.JCheckBox jCbSobreY;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTfEixoX;
    private javax.swing.JTextField jTfEixoY;
    // End of variables declaration//GEN-END:variables
}
